/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-13 13:38:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.game;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import semi.member.model.vo.*;

public final class gameMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/game/gameController.jsp", Long.valueOf(1547386596386L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("semi.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	Member loggedInMember = (Member)session.getAttribute("loggedInMember");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Noto+Serif+KR\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/game/gameMain.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/game/gameObject.css\" />\r\n");
      out.write("<style>\r\n");
      out.write("div#obj-list-container img{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\t<div id=\"background-container\">\r\n");
      out.write("\t\t<div id=\"background\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/game/gameMain/game_start_again.jpeg\" id=\"left\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"sub-background\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/game/gameMain/background.png\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<input type=\"hidden\" value=0 />\r\n");
      out.write("\t<div id=\"pause-menu-container\">\r\n");
      out.write("\t\t<div id=\"pause-menu\"></div>\r\n");
      out.write("\t\t<div id=\"store\"></div>\r\n");
      out.write("\t\t<div id=\"help\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"message\"></div>\r\n");
      out.write("\t<div id=\"pause\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/game/gameMain/pause.png\" alt=\"\" /></div>\r\n");
      out.write("\t<div id=\"inventory\">\r\n");
      out.write("\t\t<div id=\"prev\"><span>◀</span></div>\r\n");
      out.write("\t\t<div id=\"next\"><span>▶</span></div>\r\n");
      out.write("\t\t<div id=\"obj-list-container\">\r\n");
      out.write("\t\t\t<div id=\"obj-list\">\r\n");
      out.write("\t\t\t\t<div id=\"obj1\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj2\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj3\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj4\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj5\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj6\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj7\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj8\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj9\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj10\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"hint\">\r\n");
      out.write("\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/hint_paper.png\" id=\"hint-paper\" />\r\n");
      out.write("\t\t<div id=\"close-hint\">X</div>\r\n");
      out.write("\t\t<div></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"coment\">\r\n");
      out.write("\t\t<div><h2></h2></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var position = $(\"#background img\").prop(\"id\");\r\n");
      out.write("$(function(){\r\n");
      out.write("\tsetObject();\r\n");
      out.write("})\r\n");
      out.write("function setObject(){\r\n");
      out.write("\tvar position = $(\"#background img\").prop(\"id\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/game/setObject\",\r\n");
      out.write("\t\ttype: \"get\",\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\tfor(var i in data){\r\n");
      out.write("\t\t\t\tvar obj = data[i];\r\n");
      out.write("\t\t\t\tif(obj.position==position&&obj.objLevel==1){\r\n");
      out.write("\t\t\t\t\tvar html = \"<img src='");
      out.print(request.getContextPath());
      out.write("/images/game/gameMain/\"+position+\"/\"+obj.objName+\".png' id='\"+obj.objName+\"' class='obj'/>\";\r\n");
      out.write("\t\t\t\t\t$(\"#background\").append(html);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tobj_click();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function obj_click(){\r\n");
      out.write("\t$(\"#background>img\").not(\":first\").each(function(){\r\n");
      out.write("\t\tvar objName = $(this).prop(\"id\");\r\n");
      out.write("\t\t$(this).on('click', function(){\r\n");
      out.write("\t\t\tshow_coment(objName, 1);\r\n");
      out.write("\t\t\t$(\"#wrap\").addClass(\"paused\");\r\n");
      out.write("\t\t\t$(\"#wrap\").after(\"<img src='");
      out.print(request.getContextPath());
      out.write("/images/game/gameMain/clicked/\"+objName+\"_clicked.png' id='clicked' onclick='obj_reClick(\"+objName+\");'/>\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function obj_reClick(obj){\r\n");
      out.write("\tvar objName = $(obj).prop(\"id\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/game/setObject\",\r\n");
      out.write("\t\ttype: \"post\",\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\tfor(var i in data){\r\n");
      out.write("\t\t\t\tif(data[i].objName==objName){\r\n");
      out.write("\t\t\t\t\tif(data[i].secondName!=\"\"){\r\n");
      out.write("\t\t\t\t\t\t$(\"#clicked\").attr(\"src\", \"");
      out.print(request.getContextPath());
      out.write("/images/game/gameMain/\"+position+\"/\"+data[i].secondName+\".png\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#clicked\").attr(\"onclick\", \"obj_re_reClick(\"+objName+\")\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#clicked\").attr(\"id\", data[i].secondName+\"_clicked\");\r\n");
      out.write("\t\t\t\t\t\tshow_coment(objName, 2);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\t$(\"#coment\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#clicked\").remove();\r\n");
      out.write("\t\t\t\t\t\t$(\"#wrap\").removeClass(\"paused\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function obj_re_reClick(obj){\r\n");
      out.write("\tvar objName = $(obj).prop(\"id\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/game/setObject\",\r\n");
      out.write("\t\ttype: \"post\",\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\tfor(var i in data){\r\n");
      out.write("\t\t\t\tif(data[i].objName.indexOf(objName)!=-1){\r\n");
      out.write("\t\t\t\t\tif(data[i].thirdName!=\"\"){\r\n");
      out.write("\t\t\t\t\t\tshow_coment(objName, 3);\r\n");
      out.write("\t\t\t\t\t\t$(\"[id*=clicked]\").attr(\"src\", \"");
      out.print(request.getContextPath());
      out.write("/images/game/gameMain/\"+position+\"/\"+data[i].thirdName+\".png\");\r\n");
      out.write("\t\t\t\t\t\t$(\"[id*=clicked]\").attr(\"onclick\", \"obj_isLast('\"+data[i].thirdName+\"')\");\r\n");
      out.write("\t\t\t\t\t\t$(\"[id*=clicked]\").attr(\"id\", data[i].thirdName+\"_clicked\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\t$(\"[id*=clicked]\").remove();\r\n");
      out.write("\t\t\t\t\t\t$(\"#wrap\").removeClass(\"paused\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#coment\").hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function obj_isLast(objName){\r\n");
      out.write("\tif(objName.indexOf(\"diary_opened\")!=-1){\r\n");
      out.write("\t\tvar html = \"<img src='");
      out.print(request.getContextPath());
      out.write("/images/game/gameMain/left/hintnote1.png'id='hintnote1' class='obj'/>\";\r\n");
      out.write("\t\t$(\"[id*=clicked]\").after(html);\r\n");
      out.write("\t\tget_item(\"hintnote1\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/game/setObject\",\r\n");
      out.write("\t\ttype: \"post\",\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\tfor(var i in data){\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function get_item(objName){\r\n");
      out.write("\t$(\"[id*=clicked]\").next().on('click', function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/game/getObject\",\r\n");
      out.write("\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\tfor(var i in data){\r\n");
      out.write("\t\t\t\t\tif(objName==data[i].objName){\r\n");
      out.write("\t\t\t\t\t\tif(data[i].isItem==\"Y\"){\r\n");
      out.write("\t\t\t\t\t\t\tvar html = $(\"[id*=clicked]\").next().html();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#obj1\").html(html);\r\n");
      out.write("\t\t\t\t\t\t\t$(\"[id*=clicked]\").next().remove();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function show_coment(objName, rnum){\r\n");
      out.write("\tvar coment = \"\";\r\n");
      out.write("\tvar target = $(\"#coment h2\");\r\n");
      out.write("\ttarget.removeAttr(\"style\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/game/getComent\",\r\n");
      out.write("\t\ttype:\"post\",\r\n");
      out.write("\t\tdata:{\"objName\":objName,\"rnum\":rnum},\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t$(\"#coment\").show();\r\n");
      out.write("\t\t\ttarget.text(data);\r\n");
      out.write("\t\t\ttarget.parent().css(\"width\",target.outerWidth());\r\n");
      out.write("\t\t\tvar length = data.length;\r\n");
      out.write("\t\t\ttarget.attr(\"style\", \"animation:typing \"+(length/40)+\"s steps(\"+length+\", end)\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(\"#background\").fadeOut(3000);\r\n");
      out.write("setTimeout(function(){\r\n");
      out.write("\t$(\"#background img:first\").attr(\"src\", \"");
      out.print(request.getContextPath());
      out.write("/images/game/gameMain/left/background.png\")\r\n");
      out.write("\t$(\"#background\").show();\r\n");
      out.write("\t$(\"#pause\").show();\r\n");
      out.write("\t$(\".obj\").show();\r\n");
      out.write("}, 3100);\r\n");
      out.write("var record = setInterval(timer, 1000);\r\n");
      out.write("function timer(){\r\n");
      out.write("\tvar sec = $(\"[type=hidden]\").val();\r\n");
      out.write("\t$(\"[type=hidden]\").val(++sec);\r\n");
      out.write("};\r\n");
      out.write("function show_message(msg, flag){\r\n");
      out.write("\t$(\"#pause-menu-container\").addClass(\"paused\");\r\n");
      out.write("\t$(\"#message\").html(msg).show();\r\n");
      out.write("\t\r\n");
      out.write("\tif(flag){\r\n");
      out.write("\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t$(\"#pause-menu-container\").removeClass(\"paused\");\r\n");
      out.write("\t\t\t$(\"#message\").hide();\r\n");
      out.write("\t\t}, 1500);\r\n");
      out.write("\t}\r\n");
      out.write("};\r\n");
      out.write("function show_record(){\r\n");
      out.write("\tvar time = $(\"[type=hidden]\").val();\r\n");
      out.write("\tvar h = Math.floor(time/3600);\r\n");
      out.write("\tvar m = Math.floor((time%3600)/60);\r\n");
      out.write("\tvar s = (time%3600)%60;\r\n");
      out.write("\t$(\"#time\").text(h+\"시간 \"+m+\"분 \"+s+\"초\");\t\r\n");
      out.write("};\r\n");
      out.write("function show_store(){\r\n");
      out.write("\t$(\"#btn-store\").on('click', function(){\r\n");
      out.write("\t\tif(");
      out.print(loggedInMember!=null);
      out.write("){\r\n");
      out.write("\t\t\tshow_pause_menu(\"store\");\r\n");
      out.write("\t\t\t$(\"#store\").slideDown();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{show_message(\"<h2>로그인시 이용가능한 서비스입니다.</h2>\", true);}\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function show_help(){\r\n");
      out.write("\t$(\"#btn-help\").on('click', function(){\r\n");
      out.write("\t\tshow_pause_menu(\"help\");\r\n");
      out.write("\t\t$(\"#help\").slideDown();\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function active_close(){\r\n");
      out.write("\t$(\".close\").on('click', function(){\r\n");
      out.write("\t\t$(this).parent().slideUp();\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function coin_hint_refresh(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/game/coinHintRefresh\",\r\n");
      out.write("\t\ttype: \"get\",\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t$(\"#userCoin\").text(data.coin);\r\n");
      out.write("\t\t\t$(\"#hintPaper\").text(data.hintPaper);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function buy_hint_paper(){\r\n");
      out.write("\t$(\"#btn-buyHint\").on('click', function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/game/buyHint\",\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\tsuccess: function(result){\r\n");
      out.write("\t\t\t\tif(result === \"true\"){\r\n");
      out.write("\t\t\t\t\tshow_message(\"<h2>구매가 완료되었습니다.</h2>\", true);\r\n");
      out.write("\t\t\t\t\tcoin_hint_refresh();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\tshow_message(\"<h2>보유 코인이 부족합니다.</h2>\", true);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(){\r\n");
      out.write("\t\t\t\tshow_message(\"<h2>예기치 못한 오류가 발생했습니다.</h2>\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function use_hint_paper(){\r\n");
      out.write("\t$(\"#btn-useHint\").on('click', function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/game/useHint\",\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\tif(data === \"true\"){\r\n");
      out.write("\t\t\t\t\tshow_message(\"<h2>쪽지를 뽑는중입니다.</h2>\", false);\r\n");
      out.write("\t\t\t\t\tget_hint();\r\n");
      out.write("\t\t\t\t\t$(\"#message h2\").css({\"animation\":\"bling .7s\", \"animation-iteration-count\":\"3\"});\r\n");
      out.write("\t\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\t\t$(\"#message\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#hint\").show();\r\n");
      out.write("\t\t\t\t\t}, 2500);\r\n");
      out.write("\t\t\t\t\tcoin_hint_refresh();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tshow_message(\"<h2>쪽지를 구매해주세요.</h2>\", true);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(){\r\n");
      out.write("\t\t\t\tshow_message(\"<h2>예기치 못한 오류가 발생했습니다.</h2>\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function close_hint_paper(){\r\n");
      out.write("\t$(\"#close-hint\").on('click', function(){\r\n");
      out.write("\t\t$(\"#hint\").hide();\r\n");
      out.write("\t\t$(\"#hint div:last\").text(\"\");\r\n");
      out.write("\t\t$(\"#pause-menu-container\").removeClass(\"paused\");\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function get_hint(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/game/getHint\",\r\n");
      out.write("\t\ttype:\"post\",\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t$(\"#close-hint+div\").text(data);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function show_pause_menu(menuName){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/game/pauseMenu\",\r\n");
      out.write("\t\tdata: \"menuName=\"+menuName,\r\n");
      out.write("\t\ttype: \"post\",\r\n");
      out.write("\t\tdataType: \"html\",\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t$(\"#\"+menuName).html(data);\r\n");
      out.write("\t\t\tadd_event_listener();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function active_esc(){\r\n");
      out.write("\t$(\"#btn-esc\").on('click', function(){\r\n");
      out.write("\t\tshow_message(\"<h2>게임을 종료하시겠습니까?</h2><button value='1'>◎ 확인</button><button>X 취소</button>\", false);\r\n");
      out.write("\t\t$(\"#message\").find(\"button\").each(function(){\r\n");
      out.write("\t\t\t$(this).click(function(){\r\n");
      out.write("\t\t\t\tif($(this).val()==1){\r\n");
      out.write("\t\t\t\t\topener.parent.sessionStorage.removeItem(\"game\");\r\n");
      out.write("\t\t\t\t\tself.close();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t$(\"#pause-menu-container\").removeClass(\"paused\");\r\n");
      out.write("\t\t\t\t\t$(this).parent().hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("function add_event_listener(){\r\n");
      out.write("\tshow_store();\r\n");
      out.write("\tshow_help();\r\n");
      out.write("\tactive_close();\r\n");
      out.write("\tbuy_hint_paper();\r\n");
      out.write("\tuse_hint_paper();\r\n");
      out.write("\tshow_record();\r\n");
      out.write("\tactive_esc();\r\n");
      out.write("\tclose_hint_paper();\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("$(\"#next\").click(function(e){\r\n");
      out.write("\t$(this).css(\"visibility\", \"hidden\").siblings(\"#prev\").css(\"visibility\", \"visible\");\r\n");
      out.write("\t$(\"#obj-list\").animate({\"left\":\"-100%\"});\r\n");
      out.write("});\r\n");
      out.write("$(\"#prev\").click(function(){\r\n");
      out.write("\t$(this).css(\"visibility\", \"hidden\").siblings(\"#next\").css(\"visibility\", \"visible\");\r\n");
      out.write("\t$(\"#obj-list\").animate({\"left\":0});\r\n");
      out.write("});\r\n");
      out.write("$(\"#inventory\").on('click',{flag:0},function(e){\r\n");
      out.write("\tvar cnt = e.data.flag++;\r\n");
      out.write("\tif(cnt%2==0) $(this).animate({\"top\":\"80%\"});\r\n");
      out.write("\telse $(this).animate({\"top\":\"100%\"});\r\n");
      out.write("\t$(this).toggleClass('on');\r\n");
      out.write("\t$(this).children().click(function(e){\r\n");
      out.write("\t\te.stopPropagation();\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("$(\"#obj-list div\").each(function(){\r\n");
      out.write("\t$(this).on('click', function(){\r\n");
      out.write("\t\t$(this).toggleClass(\"selected\");\r\n");
      out.write("\t\t$(this).siblings().removeClass(\"selected\");\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("$(\"#pause\").on(\"click\", {flag:1}, function(e){\r\n");
      out.write("\tvar $target = $(this);\r\n");
      out.write("\tvar cnt = e.data.flag++;\r\n");
      out.write("\t$(\"#wrap div\").not(\"#pause, #pause-menu-container, #pause-menu-container div, #message\").toggleClass(\"paused\");\r\n");
      out.write("\tif(cnt%2!=0){\r\n");
      out.write("\t\t$target.children().attr(\"src\", \"");
      out.print(request.getContextPath());
      out.write("/images/game/gameMain/play.png\");\r\n");
      out.write("\t\t$(\"#pause-menu-container\").show();\r\n");
      out.write("\t\tshow_pause_menu(\"pause-menu\");\r\n");
      out.write("\t\tclearInterval(record);\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\t$target.children().attr(\"src\", \"");
      out.print(request.getContextPath());
      out.write("/images/game/gameMain/pause.png\");\r\n");
      out.write("\t\t$(\"#pause-menu-container\").hide();\r\n");
      out.write("\t\t$(\"#pause-menu\").html(\"\");\r\n");
      out.write("\t\trecord = setInterval(timer, 1000);\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(window).on('keyup', function(e){\r\n");
      out.write("\tif(e.keyCode==27){\r\n");
      out.write("\t\t$(\"#pause\").trigger(\"click\");\r\n");
      out.write("\t}\r\n");
      out.write("\tif(e.keyCode==87&&isCtrl==true){\r\n");
      out.write("\t\topener.parent.sessionStorage.removeItem(\"game\");\r\n");
      out.write("\t}\r\n");
      out.write("}).on('beforeunload', function(){\r\n");
      out.write("\tconfirm(\"\");\r\n");
      out.write("\topener.parent.sessionStorage.removeItem(\"game\");\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
