/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-08 06:55:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.game;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gameMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body, html{\r\n");
      out.write("   width: 1008px;\r\n");
      out.write("   height: 704px;\r\n");
      out.write("   padding: 0px;\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("   overflow: hidden;\r\n");
      out.write("   background: lightgray;\r\n");
      out.write("}\r\n");
      out.write("html{\r\n");
      out.write("\tbackground: black;\r\n");
      out.write("}\r\n");
      out.write("div#back-ground{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("div#back-ground img{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("div#inventory{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 70%;\r\n");
      out.write("\theight: 22%;\r\n");
      out.write("\ttop: 97%;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tbackground: lightgray;\r\n");
      out.write("\topacity: .7;\r\n");
      out.write("\tborder: 2px solid gray;\r\n");
      out.write("\tborder-radius: 22px;\r\n");
      out.write("}\r\n");
      out.write("div#inventory div#prev, div#inventory div#next{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 5%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\topacity: .5;\r\n");
      out.write("\tbackground: gray;\r\n");
      out.write("}\r\n");
      out.write("div#inventory div#prev{float:left; border-radius: 19px 0 0 0; visibility: hidden;}\r\n");
      out.write("div#inventory div#prev span{display: inline-block; margin: 57px 0 0 11px; cursor: cursor;}\r\n");
      out.write("div#inventory div#next{float:right; border-radius: 0 19px 0 0;}\r\n");
      out.write("div#inventory div#next span{display: inline-block; margin: 57px 0 0 8px; cursor: cursor;}\r\n");
      out.write("div#inventory div#prev:hover, div#inventory div#next:hover{cursor: pointer;opacity: 1;}\r\n");
      out.write("div#inventory div#prev:hover span, div#inventory div#next:hover span{transform: scale(1.2);}\r\n");
      out.write("div#inventory div#obj-list-container{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 535px;\r\n");
      out.write("\theight: 75%;\r\n");
      out.write("\ttop: 7%;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("div#inventory div#obj-list{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 200%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("div#inventory div#obj-list div{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 90px;\r\n");
      out.write("\theight: 90px;\r\n");
      out.write("\ttop: 13%;\r\n");
      out.write("\tmargin-right: 12.5px;\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("div#inventory div#obj-list div#obj5{\r\n");
      out.write("\tmargin-right: 0;\r\n");
      out.write("}\r\n");
      out.write("div#inventory:before{\r\n");
      out.write("\tcontent:\"open\"; \r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 15%; \r\n");
      out.write("\ttop: -50px;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tcolor: gray;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("div#inventory.on:before{content:\"close\";}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"back-ground\">\r\n");
      out.write("\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/game/gameMain/game_start_again.jpeg\" alt=\"\" />\r\n");
      out.write("\t<div id=\"inventory\">\r\n");
      out.write("\t\t<div id=\"prev\"><span>◀</span></div>\r\n");
      out.write("\t\t<div id=\"next\"><span>▶</span></div>\r\n");
      out.write("\t\t<div id=\"obj-list-container\">\r\n");
      out.write("\t\t\t<div id=\"obj-list\">\r\n");
      out.write("\t\t\t\t<div id=\"obj1\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj2\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj3\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj4\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj5\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj6\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj7\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj8\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj9\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"obj10\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("$(\"#back-ground img\").fadeOut(2000);\r\n");
      out.write("setTimeout(function(){\r\n");
      out.write("\t$(\"#back-ground img\").attr(\"src\", \"\").show();\r\n");
      out.write("}, 2500);\r\n");
      out.write("\r\n");
      out.write("$(\"#next\").click(function(e){\r\n");
      out.write("\t$(this).css(\"visibility\", \"hidden\").siblings(\"#prev\").css(\"visibility\", \"visible\");\r\n");
      out.write("\t$(\"#obj-list\").animate({\"left\":\"-100%\"});\r\n");
      out.write("});\r\n");
      out.write("$(\"#prev\").click(function(){\r\n");
      out.write("\t$(this).css(\"visibility\", \"hidden\").siblings(\"#next\").css(\"visibility\", \"visible\");\r\n");
      out.write("\t$(\"#obj-list\").animate({\"left\":0});\r\n");
      out.write("});\r\n");
      out.write("$(\"#inventory\").on('click',{flag:0},function(e){\r\n");
      out.write("\tvar cnt = e.data.flag++;\r\n");
      out.write("\tif(cnt%2==0) $(this).animate({\"top\":\"77%\"});\r\n");
      out.write("\telse $(this).animate({\"top\":\"97%\"});\r\n");
      out.write("\t$(this).toggleClass('on');\r\n");
      out.write("\t$(this).children().click(function(e){\r\n");
      out.write("\t\te.stopPropagation();\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
