/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-15 20:54:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board.solve;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class report_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	int commentNo = (int)request.getAttribute("commentNo");
	String commentWriter = (String)request.getAttribute("commentWriter");
	String commentContent = (String)request.getAttribute("commentContent");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=UTF-8\">\r\n");
      out.write("<title>신고하기</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/common/report.css\" />\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Amatic+SC\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 팝업크기 430 * 600 -->\r\n");
      out.write("<div id=\"logo\">Escape, if you can.</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"report-container\">\r\n");
      out.write("\t<h3 id=\"subtitle\">게시물 / 댓글 신고하기</h3>\r\n");
      out.write("\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/board/solve/solveBoardCommentReportEnd\" name=\"reportFrm\">\r\n");
      out.write("\t\t<h4>1. 게시글을 신고한 이유가 무엇인가요?</h4>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"commentNo\" value=\"");
      out.print(commentNo );
      out.write("\" />\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"commentWriter\" value=\"");
      out.print(commentWriter );
      out.write("\" />\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"commentContent\" value=\"");
      out.print(commentContent );
      out.write("\" />\r\n");
      out.write("\t\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<span class=\"explain\">(여러개를 선택할  수 있습니다.)</span><br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"reason\" value=\"reason1\"/>\r\n");
      out.write("\t\t<label for=\"reason1\">욕설 및 편파적 언행 (인종차별, 성차별 등)</label><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"reason\" value=\"reason2\"/>\r\n");
      out.write("\t\t<label for=\"reason2\">음란물 게시 및 부적절한 아이디</label><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"reason\" value=\"reason3\"/>\r\n");
      out.write("\t\t<label for=\"reason3\">도배, 광고 및 홍보</label><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"reason\" value=\"reason4\"/>\r\n");
      out.write("\t\t<label for=\"reason4\">기타</label><br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h4>2. 일어났던 일과 불쾌했던 이유를 말해주세요.</h4>\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<span class=\"explain\">(관리자가 확인 후 해당 글에 대한 처리를 도와드립니다.)</span><br><br>\r\n");
      out.write("\t\t<textarea name=\"userComment\" id=\"userComment\" cols=\"50\" rows=\"5\"></textarea>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<button type=\"button\" id=\"reportSubmit\" onclick=\"check();\">신고 접수</button>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("function check(){\r\n");
      out.write("\treason = document.getElementsByName(\"reason\");\r\n");
      out.write("\tvar check =\"\";\r\n");
      out.write("\r\n");
      out.write("\t\tcheck += reason[0].checked;\r\n");
      out.write("\t\tcheck += reason[1].checked;\r\n");
      out.write("\t\tcheck += reason[2].checked;\r\n");
      out.write("\t\tcheck += reason[3].checked;\r\n");
      out.write("\r\n");
      out.write("\tif(check==\"falsefalsefalsefalse\"){\r\n");
      out.write("\t      alert(\"최소 1개라도 선택하셔야 합니다.\");\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\t  $(\"[name=reportFrm]\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
