/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-08 12:17:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board.free;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import semi.board.free.model.vo.*;
import semi.member.model.vo.*;

public final class freeBoardView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1546947364373L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("semi.board.free.model.vo");
    _jspx_imports_packages.add("semi.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	Member loggedInMember = (Member)session.getAttribute("loggedInMember"); 

      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>You Can't Escape..</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Roboto+Slab\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Amatic+SC\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/common/header.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div id=\"top\">\r\n");
      out.write("\t\t\t<div id=\"myMenu\">\r\n");
      out.write("\t\t\t");
if(loggedInMember == null) {
      out.write("\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/login\">LOGIN</a>\r\n");
      out.write("\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t");
if("admin".equals(loggedInMember.getUserId())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/adminView\">ADMIN</a>\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberView?userId=");
      out.print(loggedInMember.getUserId());
      out.write("\">MY PAGE</a>\r\n");
      out.write("                \t&nbsp;&nbsp;\r\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\">LOGOUT</a>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"logo\">Escape, if you can.</div>\r\n");
      out.write("\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/home\">HOME</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/notice\">NOTICE</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/rank\">RANKING</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"\">SOLVE</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/board/free/freeBoardList\">FREE</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"game-start\">\r\n");
      out.write("\t\t\t<button class=\"enter-game\">ENTER GAME</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(\".enter-game\").click(function(){\r\n");
      out.write("\t\t\t//게임화면 팝업\r\n");
      out.write("\t\t\tvar url = \"");
      out.print(request.getContextPath());
      out.write("/game/gameStart?userId=");
      out.print(loggedInMember!=null?loggedInMember.getUserId():"guest");
      out.write("\";\r\n");
      out.write(" \t\t\tvar status = \"width=1024px, height=678px\";\r\n");
      out.write("\t\t\topen(url, \"\", status);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>");
      out.write('\r');
      out.write('\n');

	FreeBoard fb = (FreeBoard)request.getAttribute("fb");
	List<BoardComment> commentList = (List<BoardComment>)request.getAttribute("commentList");
	List<BoardComment> bestCommentList = (List<BoardComment>)request.getAttribute("bestCommentList");


      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/board/free/boardCommunityView.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>자유게시판</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("        <h3 style=\"color: white\">자유게시판</h3>\r\n");
      out.write("    <!--new pic-->\r\n");
      out.write("    <hr style=\"margin-bottom: 36px;\">\r\n");
      out.write("   \r\n");
      out.write("   <table class=\"sub_news\" border=\"1\" cellspacing=\"0\" summary=\"게시판의 글제목리스트\">\r\n");
      out.write("        <caption>게시판리스트</caption>\r\n");
      out.write("        <colgroup>\r\n");
      out.write("            <col width=\"30px\">\r\n");
      out.write("            <col width=\"100px\">\r\n");
      out.write("            <col width=\"30px\">\r\n");
      out.write("            <col width=\"30px\">\r\n");
      out.write("            <col width=\"30px\">\r\n");
      out.write("            <col width=\"30px\">\r\n");
      out.write("        </colgroup>\r\n");
      out.write("        \r\n");
      out.write("            <tr>\r\n");
      out.write("                <th scope=\"col\">제목</th>\r\n");
      out.write("                <td class=\"title\">\r\n");
      out.write("                       ");
      out.print(fb.getPostTitle() );
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th scope=\"col\">글쓴이</th>\r\n");
      out.write("                <td class=\"wirter\">\r\n");
      out.write("                       ");
      out.print(fb.getPostWriter() );
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th scope=\"col\">내용</th>\r\n");
      out.write("                <td class=\"content\" style=\"height: 500px;\">\r\n");
      out.write("                \r\n");
      out.write("                       ");
      out.print(fb.getPostContent() );
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"declaration\">\r\n");
      out.write("        \r\n");
      out.write("    <i>신고하기</i>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"opinion\">\r\n");
      out.write("        <div id=\"good\">\r\n");
      out.write("            <b><span id=\"like\">");
      out.print(fb.getPostLike());
      out.write("</span></b>\r\n");
      out.write("            <img src='");
      out.print(request.getContextPath());
      out.write("/images/freeBoard/like.png' onclick=\"likey('");
      out.print(fb.getPostLike());
      out.write("')\">\r\n");
      out.write("            <span id=\"likeComment\">추천</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"bad\">\r\n");
      out.write("        \t<b><span id=\"dislike\">");
      out.print(fb.getPostDislike());
      out.write("</span></b>\r\n");
      out.write("            <img src='");
      out.print(request.getContextPath());
      out.write("/images/freeBoard/dislike.png' onclick=\"disLikey('");
      out.print(fb.getPostDislike());
      out.write("')\">\r\n");
      out.write("            <span id=\"dislikeComment\">비추천</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"bestComment-container\">\r\n");
      out.write("    <hr>\r\n");
      out.write("    ");
for(BoardComment bc:bestCommentList)
                	 if(bc.getCommentLevel()==1) {
                	
      out.write("\r\n");
      out.write("        <dl style=\"margin-left: 24px;\">\r\n");
      out.write("            <d>BEST</d>\r\n");
      out.write("            <dt>\r\n");
      out.write("                ");
      out.print(bc.getCommentWriter() );
      out.write("\r\n");
      out.write("                <i>");
      out.print(bc.getCommentDate() );
      out.write("</i>\r\n");
      out.write("            </dt>\r\n");
      out.write("            \r\n");
      out.write("            <dl style=\"display: inline-flex;position: relative;left: 177px;top: -57px;\">\r\n");
      out.write("                <div class=\"button\">수정하기</div>\r\n");
      out.write("                <div class=\"button\">삭제하기</div>\r\n");
      out.write("            </dl>\r\n");
      out.write("\r\n");
      out.write("            <dl class=\"bestCommentOpinion\" style=\"position: relative;top: -120px;left: -33px;\">\r\n");
      out.write("                <span style=\"padding:10px\">추천");
      out.print(bc.getCommentLike() );
      out.write("</span>\r\n");
      out.write("                <span style=\"padding:10px\">비추천");
      out.print(bc.getCommentDislike() );
      out.write("</span>\r\n");
      out.write("                <span style=\"padding:10px\">신고하기</span>\r\n");
      out.write("            </dl>\r\n");
      out.write("\r\n");
      out.write("            <dd style=\"position: relative;top: -56px;\">\r\n");
      out.write("                \t");
      out.print(bc.getCommentContent() );
      out.write("\r\n");
      out.write("            </dd>\r\n");
      out.write("        </dl>\r\n");
      out.write("    \t<hr>\r\n");
      out.write("    \t ");
} 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"comment-container\" style=\"color:white;\">\r\n");
      out.write("        <p>\r\n");
      out.write("            <span style=\"color: red; font-size:29px;\" >");
      out.print(fb.getBoard_comment_cnt());
      out.write("</span>개의 댓글\r\n");
      out.write("        </p>\r\n");
      out.write("            <div class=\"comment-editor\">\r\n");
      out.write("                \t댓글쓰기\r\n");
      out.write("                <hr>\r\n");
      out.write("                <!-- 댓글 삽입 서블릿을 위한 폼 -->\r\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath() );
      out.write("/board/free/FreeBoardCommentInsert\" name=\"commentSubmitFrm\">\r\n");
      out.write("                <input type=\"hidden\" name=\"ref\" value=\"");
      out.print(fb.getPostNo() );
      out.write("\" />\r\n");
      out.write("                <input type=\"hidden\" name=\"userId\" value=\"userId\"/>\r\n");
      out.write("                <input type=\"hidden\" name=\"commentLevel\" value=\"1\" />\r\n");
      out.write("                <input type=\"hidden\" name=\"commentRef\" value=\"0\" />\r\n");
      out.write("             \t<!-- <input type=\"checkBox\" name=\"secret\"/><label for=\"secret\">비밀글</label> -->\r\n");
      out.write("                <textarea name=\"boardCommentContent\" cols=\"60\" rows=\"3\" style=\"margin: 11px;margin-bottom: -78px;width: 800px;height: 113px;resize:none;\"></textarea>\r\n");
      out.write("                </form>\r\n");
      out.write("                <div class=\"commentSubmit\" onclick=\"insertComment();\" style=\"cursor: pointer;\">등록</div>\r\n");
      out.write("               \r\n");
      out.write("            </div><!-- end of . comment-editor -->\r\n");
      out.write("            \r\n");
      out.write("            <!-- 댓글 목록 테이블 -->\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"commentList\">\r\n");
      out.write("                <hr>\r\n");
      out.write("                ");
for(int i=0; i<commentList.size(); i++){
                	BoardComment bc = commentList.get(i);
                	
                	 if(bc.getCommentLevel()==1) {
                	
      out.write("\r\n");
      out.write("                 <dl class=\"comment-Area\">\r\n");
      out.write("                    <dt class=\"commentWriter\">\r\n");
      out.write("                        ");
      out.print(bc.getCommentWriter());
      out.write("\r\n");
      out.write("                        <i>");
      out.print(bc.getCommentDate() );
      out.write("</i>\r\n");
      out.write("                    </dt>\r\n");
      out.write("                    \r\n");
      out.write("                \t<dl style=\"display: inline-flex; position: relative; left: 177px; top: -46px;\">\r\n");
      out.write("                        <input type=\"hidden\" value=");
      out.print(bc.getCommentNo() );
      out.write(" id=\"commentNo\" />\r\n");
      out.write("                        <input type=\"hidden\" value=");
      out.print(bc.getCommentContent() );
      out.write(" id=\"commentContent\" />\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"commentUpdate\" no=\"");
      out.print(i);
      out.write("\" style=\"cursor:pointer;\">수정하기</div>\r\n");
      out.write("                        <div class=\"button\"  onclick=\"updateCommentEnd();\" no=\"");
      out.print(i );
      out.write("\" id=\"commentUpdateEnd\" style=\"cursor:pointer;\">수정완료</div>\r\n");
      out.write("                        <div class=\"button\" id=\"commentDeleteBtn\" onclick=\"deleteComment();\">삭제하기</div>\r\n");
      out.write("        \t\t\t</dl>\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t\t<!-- 댓글 삭제를 위한 폼 -->\r\n");
      out.write("                    <form action=\"");
      out.print(request.getContextPath());
      out.write("/board/free/freeBoardCommentDelete\" name=\"commentDeleteFrm\">\r\n");
      out.write("                    <input type=\"hidden\" value=\"");
      out.print(bc.getCommentNo() );
      out.write("\" name=\"commentNo\"/>\r\n");
      out.write("                    <input type=\"hidden\" value=\"");
      out.print(fb.getPostNo() );
      out.write("\" name=\"postNo\" id=\"postNo\"/>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    \r\n");
      out.write("        \t\t\t\r\n");
      out.write("                    <dl class=\"bestCommentOpinion\">\r\n");
      out.write("                            <dl class=\"CommentOpinion\">\r\n");
      out.write("             \t\t\t\t\t\t 추천\t \r\n");
      out.write("                                    <span style=\"padding:10px\" id=\"comment1Like\" onclick=\"comment1Like('");
      out.print(bc.getCommentLike());
      out.write("');\">");
      out.print(bc.getCommentLike());
      out.write("</span>\r\n");
      out.write("                                    <span style=\"padding:10px\">비추천");
      out.print(bc.getCommentDislike());
      out.write("</span>\r\n");
      out.write("                                    <span style=\"padding:10px\">신고하기</span>\r\n");
      out.write("                                    \r\n");
      out.write("                            </dl>\r\n");
      out.write("                    </dl>\r\n");
      out.write("        \r\n");
      out.write("                    <dd class=\"comment_\">\r\n");
      out.write("                    <textarea name=\"comment-Update\" no=\"");
      out.print(i);
      out.write("\" class=\"comment-Update\" cols=\"60\" rows=\"3\" style=\"margin: 11px;margin-bottom: -78px;width: 1000px;height: 113px;resize:none;\">");
      out.print(bc.getCommentContent() );
      out.write("</textarea>\r\n");
      out.write("                    <dd class=\"comment-Content\">\r\n");
      out.write("                            ");
      out.print(bc.getCommentContent() );
      out.write("\r\n");
      out.write("                    </dd>\r\n");
      out.write("                    \r\n");
      out.write("       \t\t\t\t\r\n");
      out.write("                    <span class=\"level2CommentWrite\" level2No=\"");
      out.print(i);
      out.write("\">답글쓰기</span> \r\n");
      out.write("           </div> \r\n");
      out.write("         <hr /> \r\n");
      out.write("                    \t\t\r\n");
      out.write("              ");
 }
		else{ 
      out.write("   \r\n");
      out.write("                    \r\n");
      out.write("                  \r\n");
      out.write("                    \r\n");
      out.write("               \r\n");
      out.write("                   \r\n");
      out.write("                   <!-- <div class=\"level2CommentListDiv\" commentListNo=\"");
      out.print(i);
      out.write("\"> -->\r\n");
      out.write("\r\n");
      out.write("                   <div class=\"level2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(bc.getCommentNo() );
      out.write("\" /> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"level2_area\" level2No=\"");
      out.print(i);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"reply_icon\"> <img src='");
      out.print(request.getContextPath());
      out.write("/images/freeBoard/commentReply.png'></span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"info\">");
      out.print(bc.getCommentWriter() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"level2Comment\">");
      out.print(bc.getCommentContent() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"level2Date\">");
      out.print(bc.getCommentDate() );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"level2Report\">신고하기</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"level2Like\">추천 23</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"level2Dislike\">비추천 0</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t<hr />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t");
}
          } 
      out.write("   \r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t\t<div class=\"level2CommentWriteDiv\">\r\n");
      out.write("                    \t<textarea class=\"level2CommentWrite-textArea\" cols=\"60\" rows=\"3\"></textarea>\r\n");
      out.write("                    \t<div class=\"level2Commentsubmit\" >등록</div>\r\n");
      out.write("                 \t</div> \r\n");
      out.write("                </div><!--level2 div 끝  -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("               </div><!-- level2CommentListDiv 끝 -->\r\n");
      out.write("             </dl>\r\n");
      out.write("        </div> <!-- end of . comment-container -->\r\n");
      out.write("       \r\n");
      out.write("        <div class=\"button\" id=\"update\" onclick=\"updateBoard();\">수정</div>\r\n");
      out.write("    \t<div class=\"button\" id=\"delete\" onclick=\"deleteBoard();\">삭제</div>\r\n");
      out.write("   \t\t<div class=\"button\" id=\"goList\">목록</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath());
      out.write("/board/free/freeBoardDelete\" name=\"boardDelFrm\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"postNo\" value=\"");
      out.print(fb.getPostNo());
      out.write("\" id=\"postNo\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"rName\" value=\"");
      out.print(fb.getPostRenamedFile());
      out.write("\" />\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction updateBoard(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/board/free/freeBoardUpdate?postNo=");
      out.print(fb.getPostNo());
      out.write("\";\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction deleteBoard(){\r\n");
      out.write("\t\tif(!confirm(\"정말 게시글을 삭제하시겠습니까?\")){\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"[name=boardDelFrm]\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction insertComment(){\r\n");
      out.write("\t\t$(\"[name=commentSubmitFrm]\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("    $(\".commentUpdate\").on(\"click\", function(){\r\n");
      out.write("    \t\r\n");
      out.write("    \tvar no = $(this).attr(\"no\");\r\n");
      out.write("     \tconsole.log(\"no=\"+no);\r\n");
      out.write("    \tconsole.log($(\"textarea[no=\"+no+\"]\")); \r\n");
      out.write("    \t\r\n");
      out.write("    \t$(\".comment-Content[no=\"+no+\"]\").hide();  //원래댓글\r\n");
      out.write("    \t$(\".comment-Update[no=\"+no+\"]\").css(\"display\",\"inline\"); //수정하기위한 text area\r\n");
      out.write("    \t$(\"#commentUpdateEnd[no=\"+no+\"]\").css(\"display\",\"inline\"); //수정완료 버튼\r\n");
      out.write("\t\r\n");
      out.write("       \r\n");
      out.write("        $(\".commentUpdate\").css(\"display\",\"none\"); //수정하기 버튼\r\n");
      out.write("        $(\"#commentDeleteBtn\").css(\"display\",\"none\"); //삭제하기 버튼\r\n");
      out.write("        $(\"#level2CommentList\").css(\"display\",\"none\"); //답글보기 버튼\r\n");
      out.write("        $(\"#level2CommentWrite\").css(\"display\",\"none\"); //답글쓰기 버튼\r\n");
      out.write("        $(\"#line\").css(\"display\",\"none\"); // | \r\n");
      out.write("    \t/* $(this).find(\"#comment-Content\").hide();  //원래댓글\r\n");
      out.write("    \t$(this).find(\".comment-Update\").css(\"display\",\"inline\"); //수정하기위한 text area\r\n");
      out.write("    \t$(this).find(\"#commentUpdateEnd\").css(\"display\",\"inline\"); //수정완료 버튼\r\n");
      out.write("\t\r\n");
      out.write("       \r\n");
      out.write("        $(this).find(\".commentUpdate\").css(\"display\",\"none\"); //수정하기 버튼\r\n");
      out.write("        $(this).find(\"#commentDeleteBtn\").css(\"display\",\"none\"); //삭제하기 버튼\r\n");
      out.write("        $(this).find(\"#level2CommentList\").css(\"display\",\"none\"); //답글보기 버튼\r\n");
      out.write("        $(this).find(\"#level2CommentWrite\").css(\"display\",\"none\"); //답글쓰기 버튼\r\n");
      out.write("        $(this).find(\"#line\").css(\"display\",\"none\"); // |  */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        var commentUpdate = $(\".comment-Update\").val();\r\n");
      out.write("        var commentNo = $(\"#commentNo\").val();\r\n");
      out.write("        var postNo = $(\"#postNo\").val();\r\n");
      out.write("    });    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write(" \t$(\".level2Commentsubmit\").on(\"click\", function(){\r\n");
      out.write(" \t\tvar level2Comment = $(\".level2CommentWrite-textArea\").val();\r\n");
      out.write(" \t\tvar ref = $(\"input[name=ref]\").val(); //해당 글번호\r\n");
      out.write(" \t\tvar commentRef = $(\".level2 input\").val() //대댓글의 해당 댓글번호 \r\n");
      out.write(" \t\tvar commentWriter = $(\"input[name=userId]\").val(); //유저아이디\r\n");
      out.write(" \t\tvar commentLevel = 2; //대댓글\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tconsole.log(\"level2Comment=\"+level2Comment);\r\n");
      out.write(" \t\tconsole.log(\"ref=\"+ref);\r\n");
      out.write(" \t\tconsole.log(\"commentRef=\"+commentRef);\r\n");
      out.write(" \t\tconsole.log(\"commentWriter=\"+commentWriter);\r\n");
      out.write(" \t\tconsole.log(\"commentLevel=\"+commentLevel);\r\n");
      out.write("\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t $.ajax({\r\n");
      out.write(" \t\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/board/free/freeBoardComment2.do\",\r\n");
      out.write("     \t\tdata:{level2Comment:level2Comment, ref:ref, commentRef:commentRef, commentWriter:commentWriter,  commentLevel:commentLevel},\r\n");
      out.write("     \t\tsuccess:function(data){\r\n");
      out.write("     \t\t\t\r\n");
      out.write("     \t\t\tvar data_split = data.split(\"/\");\r\n");
      out.write("     \t\t\tconsole.log(data_split);\r\n");
      out.write("     \t\t\tvar comment2UserId = data_split[0];\r\n");
      out.write("     \t\t\tvar comment2Date = data_split[1];\r\n");
      out.write("     \t\t\tvar comment2Content = data_split[2];\r\n");
      out.write("     \t\t\t\r\n");
      out.write("     \t\t\t\r\n");
      out.write("     \t\t\tvar reply_icon = $(\".reply_icon\");\r\n");
      out.write("     \t\t\tvar info = $(\".info\");\r\n");
      out.write("     \t\t\tvar level2Comment = $(\".level2Comment\");\r\n");
      out.write("     \t\t\tvar level2Date = $(\".level2Date\");\r\n");
      out.write("     \t\t\t\r\n");
      out.write("     \t\t\tvar html = \"\";\r\n");
      out.write("     \t  \t\thtml+=reply_icon+\"<img src='");
      out.print(request.getContextPath());
      out.write("/images/freeBoard/commentReply.png'>\";\r\n");
      out.write("     \t\t\thtml+=info+comment2UserId;\r\n");
      out.write("     \t\t\thtml+=level2Comment+comment2Content;\r\n");
      out.write("     \t\t\thtml+=level2Date+comment2Content;\r\n");
      out.write("     \t\t\t\r\n");
      out.write("     \t\t\t$(\".level2_area\").insertAfter(html);\r\n");
      out.write("     \t\t\t/* \t$(\".reply_icon\").insertAfter();\r\n");
      out.write("     \t\t\t\t$(\".info\").insertAfter(comment2UserId);\r\n");
      out.write("     \t\t\t\t$(\".level2Comment\").insertAfter(comment2Content);\r\n");
      out.write("     \t\t\t\t$(\".level2Date\").insertAfter(comment2Date); */\r\n");
      out.write("     \t\t\t\r\n");
      out.write("     \t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("   \r\n");
      out.write("     \t\t\t\r\n");
      out.write("     \t\t\t\r\n");
      out.write("     \t\t/* \t$(\".level2_area\").append(html); */\r\n");
      out.write("     \t\t\t\r\n");
      out.write("     \t\t\t\r\n");
      out.write("     \t\t");
      out.write("\r\n");
      out.write("     \t\t}\r\n");
      out.write(" \t\t}); \r\n");
      out.write(" \t});\r\n");
      out.write("    \r\n");
      out.write("    $(\".level2CommentWrite\").on(\"click\", function(){\r\n");
      out.write("    \t\r\n");
      out.write("    \t/* var no = $(\"input[name=commentNo]\").val(); */\r\n");
      out.write("    \tvar no = $(this).attr(\"level2No\");\r\n");
      out.write("    \tconsole.log(\"no\"+no);\r\n");
      out.write("    \t\r\n");
      out.write("    \r\n");
      out.write("    \t$(\".level2_area[level2No=\"+no+\"]\").css(\"display\",\"inline\");\r\n");
      out.write("    \t$(\".level2CommentWriteDiv\").css(\"display\",\"inline\");\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    function updateCommentEnd(){    \r\n");
      out.write("        var commentNo = $(\"#commentNo\").val();\r\n");
      out.write("        var commentUpdate = $(\".comment-Update\").val();\r\n");
      out.write("        location.href = \"");
      out.print(request.getContextPath());
      out.write("/board/free/freeBoardCommentUpdate?postNo=");
      out.print(fb.getPostNo());
      out.write("&commentNo=\"+commentNo+\"&commentUpdate=\"+commentUpdate;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function deleteComment(){\r\n");
      out.write("        if(!confirm(\"댓글을 정말로 삭제하시겠습니까?\")){\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        $(\"[name=commentDeleteFrm]\").submit();\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("    function comment1Like(item){\r\n");
      out.write("    \tvar commentNo =  $(\"#commentNo\").val(); \r\n");
      out.write("    \t/* var no = $(\"#comment1Like\").selected;\r\n");
      out.write("     \tconsole.log(\"no=\"+no); */\r\n");
      out.write("    \tvar here = $(\"#comment1Like\", this); \r\n");
      out.write("    \t//var flag= false;\r\n");
      out.write("    \r\n");
      out.write("    \t//console.log(\"comment1Like\",item);\r\n");
      out.write("    \t if(!confirm(\"해당 댓글을 추천하시겠습니까?\")){\r\n");
      out.write("    \t\treturn;\r\n");
      out.write("    \t} \r\n");
      out.write("    \t \r\n");
      out.write("    \t $.ajax({\r\n");
      out.write("     \t\turl:\"");
      out.print(request.getContextPath());
      out.write("/board/free/freeBoardComment1Like.do\",\r\n");
      out.write("     \t\tdata:{commentNo:commentNo, commentLikey:item},\r\n");
      out.write("     \t\tsuccess:function(data){\r\n");
      out.write("     \t\t\t$(\"#comment1Like\").attr( 'name', 'here' );\r\n");
      out.write("     \t\t\t$(\"#comment1Like[name=here]\").html(data);\r\n");
      out.write("     \t\r\n");
      out.write("     \t\t}\r\n");
      out.write("     \t\t\r\n");
      out.write("     \t});\r\n");
      out.write("    \t \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function likey(item){\r\n");
      out.write("    \tvar postNo =  $(\"#postNo\").val(); \r\n");
      out.write("    \tconsole.log(\"postNo\",postNo);\r\n");
      out.write("    \tif(!confirm(\"해당 글을 추천하시겠습니까?\")){\r\n");
      out.write("    \t\treturn;\r\n");
      out.write("    \t} \r\n");
      out.write("    \t  \r\n");
      out.write("  \t\t$.ajax({\r\n");
      out.write("     \t\turl:\"");
      out.print(request.getContextPath());
      out.write("/board/free/freeBoardLike.do\",\r\n");
      out.write("     \t\tdata:{postNo:postNo, likey:item},\r\n");
      out.write("     \t\tsuccess:function(data){\r\n");
      out.write("     \t\t\t$(\"#like\").html(data);\r\n");
      out.write("     \t\t}\r\n");
      out.write("     \t});  \r\n");
      out.write("    \t \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function disLikey(item){\r\n");
      out.write("    \tvar postNo =  $(\"#postNo\").val(); \r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \tif(!confirm(\"해당 글을 비추천하시겠습니까?\")){\r\n");
      out.write("    \t\treturn;\r\n");
      out.write("    \t} \r\n");
      out.write("    \t \r\n");
      out.write("    \r\n");
      out.write("    \t\r\n");
      out.write("    \t\t$.ajax({\r\n");
      out.write("\t     \t\turl:\"");
      out.print(request.getContextPath());
      out.write("/board/free/freeBoardDisike.do\",\r\n");
      out.write("\t     \t\tdata:{postNo:postNo, dislikey:item},\r\n");
      out.write("\t     \t\tsuccess:function(data){\r\n");
      out.write("\t     \t\t\t$(\"#dislike\").html(data);\r\n");
      out.write("\t     \t\t\t\r\n");
      out.write("\t     \t\t}\r\n");
      out.write("\t     \t\t\r\n");
      out.write("\t     \t});\r\n");
      out.write("    \t\r\n");
      out.write("    \t\tconsole.log(flag);\r\n");
      out.write("    }\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
