/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-17 09:31:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board.free;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import semi.board.free.model.vo.*;

public final class temporaryBox_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("semi.board.free.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

   List<TemporaryData> boxList = (List<TemporaryData>)request.getAttribute("boxList");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<title>임시보관함</title>\r\n");
      out.write("</head>\r\n");
      out.write(" <style>\r\n");
      out.write("        body{\r\n");
      out.write("            background-color: black;\r\n");
      out.write("        }\r\n");
      out.write("        .sub_news, .sub_news th, .sub_news td{\r\n");
      out.write("             border: 0\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sub_news a{\r\n");
      out.write("            color: #383838;\r\n");
      out.write("            text-decoration: none\r\n");
      out.write("        }\r\n");
      out.write("        .sub_news{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-bottom: 1px #999;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            table-layout: fixed;\r\n");
      out.write("        }\r\n");
      out.write("        .sub_news caption{\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        .sub_news th{\r\n");
      out.write("            padding: 5px 0 6px;\r\n");
      out.write("            border-top: solid 1px #999;\r\n");
      out.write("            border-bottom: solid 1px #b2b2b2;\r\n");
      out.write("            background-color: #f1f1f4;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-weight:bold;\r\n");
      out.write("            line-height: 20px;\r\n");
      out.write("            vertical-align: top;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sub_news td{\r\n");
      out.write("            padding: 8px 0 9px;\r\n");
      out.write("            border-bottom : solid 1px #d2d2d2;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            line-height:18px;\r\n");
      out.write("        }\r\n");
      out.write("        .sub_news .date,.sub_news .views{\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            font-family: Tahoma;\r\n");
      out.write("            font-size: 11px;\r\n");
      out.write("            line-height: normal;\r\n");
      out.write("        }\r\n");
      out.write("        .sub_news .title{\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            padding-left: 15px;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("        }\r\n");
      out.write("        .sub_news .title .pic, .sub_news .title .new{\r\n");
      out.write("            margin: 0 0 2px;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container{\r\n");
      out.write("           /* border: 1px solid red;*/\r\n");
      out.write("           width: 550px;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        .sub_news tbody tr:hover .title{\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        .sub_news tbody tr:hover{\r\n");
      out.write("        background-color : #f1f1f4; \r\n");
      out.write("        cursor: pointer;  \r\n");
      out.write("        }\r\n");
      out.write("       #search,#searchVal{\r\n");
      out.write("            border: 1px solid #999;\r\n");
      out.write("            width: 50px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            padding: 5px 0 6px;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("            margin-top: 12px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("         #search:hover{\r\n");
      out.write("            background-color :#d2d2d2;\r\n");
      out.write("            cursor: pointer; \r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         #write:hover{\r\n");
      out.write("            background-color :#d2d2d2;\r\n");
      out.write("            cursor: pointer; \r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         #write{\r\n");
      out.write("            float: right;\r\n");
      out.write("            border: 1px solid #999;\r\n");
      out.write("            width: 50px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            padding: 5px 0 6px;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("            margin-bottom:  12px;\r\n");
      out.write("            margin-top: 7px;  \r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         #searchVal{\r\n");
      out.write("            border: 1px solid #999;\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            padding: 5px 0 6px;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("           \r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         #searchOpt{\r\n");
      out.write("            border: 1px solid #999;\r\n");
      out.write("            width: 60px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            padding: 5px 0 6px;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("            margin-top: 12px;  \r\n");
      out.write("         }\r\n");
      out.write("         tr .best{\r\n");
      out.write("            background-color :#d2d2d2;\r\n");
      out.write("\r\n");
      out.write("         }\r\n");
      out.write("        #search{\r\n");
      out.write("            width: 50px;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 286px;\r\n");
      out.write("            top: 299px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"width:550px;\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h4 style=\"color:white\">임시보관함</h4>\r\n");
      out.write("    <hr>\r\n");
      out.write("    \r\n");
      out.write("   <table class=\"sub_news\" id=\"best3List\" border=\"1\" cellspacing=\"0\" summary=\"베스트3\">\r\n");
      out.write("        <caption>게시판리스트</caption>\r\n");
      out.write("        <colgroup>\r\n");
      out.write(" \r\n");
      out.write("            <col width=\"100px\">\r\n");
      out.write("            <col width=\"30px\">\r\n");
      out.write("          \r\n");
      out.write("        </colgroup>\r\n");
      out.write("            <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("               \r\n");
      out.write("                <th scope=\"col\">제목</th>\r\n");
      out.write("                <th scope=\"col\">날짜</th>\r\n");
      out.write("              \r\n");
      out.write("            </tr>\r\n");
      out.write("         </thead>\r\n");
      out.write("\r\n");
      out.write("             \r\n");
for(int i=0; i<boxList.size(); i++) {
	TemporaryData td = boxList.get(i);



      out.write("\r\n");
      out.write("\r\n");
      out.write("         <tbody>\r\n");
      out.write("            <table class=\"sub_news\" border=\"1\" cellspacing=\"0\" summary=\"게시판의 글제목리스트\">\r\n");
      out.write("                    <colgroup>\r\n");
      out.write("                       \r\n");
      out.write("                        <col width=\"100px\">\r\n");
      out.write("                        <col width=\"30px\">\r\n");
      out.write("                  \r\n");
      out.write("                    </colgroup>\r\n");
      out.write("                    \r\n");
      out.write("            ");
if(boxList == null || boxList.isEmpty()) { 
      out.write("\r\n");
      out.write("             \t<tr>\r\n");
      out.write("               \t\t<td colspan=\"6\" align=\"center\">임시저장된 데이터가 없습니다.</td>\r\n");
      out.write("           \t\t </tr>\r\n");
      out.write("            ");
} else {
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td class=\"title\">\r\n");
      out.write("                ");
if(td.getDataTitle()==null){ 
      out.write("\r\n");
      out.write("                \t\r\n");
      out.write("                \t<span onclick=\"check(");
      out.print(td.getDataNo() );
      out.write(',');
      out.write('\'');
      out.print(td.getDataTitle() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(td.getDataContent() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(td.getDataOriginalFile() );
      out.write("');\">제목없음</span>\r\n");
      out.write("                \t<input type=\"hidden\" value=\"제목없음\"  no=\"");
      out.print(i);
      out.write("\"/>\r\n");
      out.write("                ");
} else {
      out.write("\r\n");
      out.write("                \t<span onclick=\"check(");
      out.print(td.getDataNo() );
      out.write(',');
      out.write('\'');
      out.print(td.getDataTitle() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(td.getDataContent() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(td.getDataOriginalFile() );
      out.write("');\">");
      out.print(td.getDataTitle() );
      out.write("</span>\r\n");
      out.write("    \t\t\t\t<input type=\"hidden\" value=\"");
      out.print(td.getDataTitle() );
      out.write("\" no=\"");
      out.print(i);
      out.write("\"/>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("\r\n");
      out.write("                <td class=\"date\">\r\n");
      out.write("                ");
      out.print(td.getDataDate() );
      out.write("\r\n");
      out.write("               \t<input type=\"hidden\" value=\"");
      out.print(td.getDataDate() );
      out.write("\"  no=\"");
      out.print(i);
      out.write("\"/>\r\n");
      out.write("                </td>\r\n");
      out.write("            \r\n");
      out.write("            </tr>\r\n");
      out.write("      \r\n");
      out.write("         </tbody>\r\n");
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("  </div> \r\n");
      out.write("<script>\r\n");
      out.write("function check(item1, item2, item3, item4){\r\n");
      out.write("\tvar dataNo = item1;\r\n");
      out.write("\tvar dataTitle = item2;\r\n");
      out.write("\tvar dataContent = item3;\r\n");
      out.write("\tvar fileName = item4;\r\n");
      out.write("    opener.location.href= \"");
      out.print(request.getContextPath());
      out.write("/board/free/freeBoardTemporaryForm?dataNo=\"+dataNo+\"&dataTitle=\"+dataTitle+\"&dataContent=\"+dataContent+\"&file=\"+fileName;\r\n");
      out.write("    window.close();\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
} }
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
